version:	"0013--07-Nov-2022"
copyright:	"2022"
title:		"OS222: Operating Systems 2022-2"
author:		"Feru P. Kartajaya"
githubrepo:     "https://github.com/ferupk/os222"
mylog:		"/TXT/mylog.txt"
mypubkey:	"/TXT/mypubkey.txt"
tarball:	"https://os.vlsm.org/Log/ferupk.tar.bz2.txt"
encoding:	UTF-8
markdown:	kramdown
input:		GFM
hard_wrap:	false
github:		[metadata]
